FROM node:latest

# Set environment variables
ARG BACKEND_WS_URI
ENV BACKEND_WS_URI=${BACKEND_WS_URI}

ARG BACKEND_GQL_URI
ENV BACKEND_GQL_URI=${BACKEND_GQL_URI}

# Set working directory
WORKDIR /app

# Copy frontend files
COPY . /app/frontend

# Move into frontend directory
WORKDIR /app/frontend

# Install dependencies
RUN npm install
RUN npm build
# Expose ports
EXPOSE 3000

# Command to run your application
CMD ["npm", "run", "dev"]
