version: '3'

services:
  frontend:
    # image: mayur0502/code-colab-frontend:v1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_WS_URI=http://localhost:4000
      - REACT_APP_BACKEND_GQL_URI=http://localhost:8080
    container_name: colab-frontend
  backend:
    # image: mayur0502/code-colab-backend:v1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4000:4000"
    container_name: colab-backend
    env_file:
      - ./backend/.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
